"""add tags column to tasks

Revision ID: cc62c0a78c90
Revises: 3900bcc65bc0
Create Date: 2025-09-23 22:38:04.666529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc62c0a78c90'
down_revision: Union[str, Sequence[str], None] = '3900bcc65bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tags')
    # ### end Alembic commands ###
